# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""Python code generator for CDDL types.

Generates Python dataclasses, Enums, and Union types from CDDL AST.
"""

from . import ast, type_guards


class PythonCodeGenerator:
    """Generates Python code from CDDL AST."""

    LICENSE_HEADER = """# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

\"\"\"Auto-generated from W3C WebDriver BiDi CDDL specification.

DO NOT EDIT THIS FILE MANUALLY. Regenerate using:
    python -m cddl.main generate-all
\"\"\"

from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, Dict, List, Optional, Union, Literal
import json
"""

    def __init__(self, strict_mode: bool = False):
        """Initialize code generator.
        
        Args:
            strict_mode: If True, validate all fields strictly
        """
        self.strict_mode = strict_mode
        self.type_imports: set[str] = set()
        self.generated_code: dict[str, str] = {}

    def generate_module(self, module: ast.CddlModule) -> str:
        """Generate Python code for an entire module.
        
        Args:
            module: CddlModule AST node
            
        Returns:
            Generated Python code for the module
        """
        lines = [self.LICENSE_HEADER]
        
        # Generate all types in the module
        code_blocks = []
        for type_name, cddl_type in sorted(module.types.items()):
            code = self._generate_type(cddl_type, module.name)
            if code:
                code_blocks.append(code)
        
        # Combine all code blocks
        if code_blocks:
            lines.append("\n\n".join(code_blocks))
        
        return "\n".join(lines)

    def _generate_type(self, cddl_type: ast.CddlType, module_name: str = "") -> str | None:
        """Generate Python code for a single type.
        
        Args:
            cddl_type: CddlType AST node
            module_name: Name of the module containing this type
            
        Returns:
            Generated Python code or None if type should be skipped
        """
        if isinstance(cddl_type, ast.CddlObject):
            return self._generate_dataclass(cddl_type)
        elif isinstance(cddl_type, ast.CddlEnum):
            return self._generate_enum(cddl_type)
        elif isinstance(cddl_type, ast.CddlUnion):
            return self._generate_union(cddl_type)
        elif isinstance(cddl_type, ast.CddlArray):
            # Array types are handled inline, not as separate classes
            return None
        elif isinstance(cddl_type, ast.CddlType) and cddl_type.is_primitive:
            # Primitive types don't need generation
            return None
        
        return None

    def _generate_dataclass(self, obj_type: ast.CddlObject) -> str:
        """Generate a dataclass from a CddlObject.
        
        Args:
            obj_type: CddlObject AST node
            
        Returns:
            Generated dataclass code
        """
        class_name = self._sanitize_name(obj_type.name)
        lines = ["@dataclass"]
        
        # Class definition
        if obj_type.extensible:
            lines.append(f"class {class_name}:")
            lines.append(f'    """Extensible type: {obj_type.name}."""')
        else:
            lines.append(f"class {class_name}:")
            if obj_type.description:
                lines.append(f'    """{obj_type.description}"""')
            else:
                lines.append('    """Auto-generated from WebDriver BiDi CDDL."""')
        
        # Generate fields
        if obj_type.fields:
            for field in obj_type.fields:
                field_name = type_guards._snake_to_camel(field.name)  # Use snake_case for Python
                field_type = self._get_python_type(field.type)
                
                if field.optional:
                    lines.append(f"    {field_name}: Optional[{field_type}] = None")
                else:
                    lines.append(f"    {field_name}: {field_type}")
        else:
            # Empty dataclass
            lines.append("    pass")
        
        # Add to_json method
        lines.append("")
        lines.append("    def to_json(self) -> Dict[str, Any]:")
        lines.append('        """Convert to JSON-serializable dict."""')
        lines.append("        result = {}")
        for field in obj_type.fields:
            python_name = type_guards._snake_to_camel(field.name)
            json_name = field.name  # Use original camelCase name
            lines.append(f"        if self.{python_name} is not None:")
            lines.append(f"            result['{json_name}'] = self.{python_name}")
        lines.append("        return result")
        
        # Add from_json classmethod
        lines.append("")
        lines.append("    @classmethod")
        lines.append("    def from_json(cls, data: Dict[str, Any]) -> '{class_name}':")
        lines.append("        \"\"\"Create from JSON dict with lenient parsing.\"\"\"")
        lines.append("        kwargs = {}")
        for field in obj_type.fields:
            python_name = type_guards._snake_to_camel(field.name)
            json_name = field.name
            lines.append(f"        if '{json_name}' in data:")
            lines.append(f"            kwargs['{python_name}'] = data['{json_name}']")
        lines.append("        return cls(**kwargs)")
        
        return "\n".join(lines)

    def _generate_enum(self, enum_type: ast.CddlEnum) -> str:
        """Generate an Enum from a CddlEnum.
        
        Args:
            enum_type: CddlEnum AST node
            
        Returns:
            Generated enum code
        """
        class_name = self._sanitize_name(enum_type.name)
        lines = [f"class {class_name}(str, Enum):"]
        lines.append('    """Auto-generated enum from WebDriver BiDi CDDL."""')
        
        if enum_type.values:
            for i, value in enumerate(enum_type.values):
                # Enum members must be valid Python identifiers
                member_name = self._sanitize_identifier(value)
                lines.append(f"    {member_name} = \"{value}\"")
        else:
            lines.append("    pass")
        
        return "\n".join(lines)

    def _generate_union(self, union_type: ast.CddlUnion) -> str:
        """Generate Union handling code.
        
        Args:
            union_type: CddlUnion AST node
            
        Returns:
            Generated union code (as type alias)
        """
        class_name = self._sanitize_name(union_type.name)
        variant_types = []
        
        for variant in union_type.variants:
            variant_type = self._get_python_type(variant.type)
            variant_types.append(variant_type)
        
        # Generate as type alias
        union_str = " | ".join(variant_types)
        return f"{class_name} = Union[{', '.join(variant_types)}]"

    def _get_python_type(self, cddl_type: ast.CddlType) -> str:
        """Convert CDDL type to Python type string.
        
        Args:
            cddl_type: CddlType to convert
            
        Returns:
            Python type string
        """
        if not cddl_type:
            return "Any"
        
        if isinstance(cddl_type, ast.CddlArray):
            item_type = self._get_python_type(cddl_type.item_type)
            return f"List[{item_type}]"
        
        if isinstance(cddl_type, ast.CddlObject):
            return self._sanitize_name(cddl_type.name) if cddl_type.name else "Dict[str, Any]"
        
        if isinstance(cddl_type, ast.CddlUnion):
            variants = [self._get_python_type(v.type) for v in cddl_type.variants]
            return f"Union[{', '.join(variants)}]"
        
        if isinstance(cddl_type, ast.CddlEnum):
            return self._sanitize_name(cddl_type.name)
        
        if cddl_type.is_primitive:
            if cddl_type.base_type == "string":
                return "str"
            elif cddl_type.base_type == "number":
                return "int"
            elif cddl_type.base_type == "number_range":
                return "int"
            elif cddl_type.base_type in ("bool", "boolean"):
                return "bool"
        
        if cddl_type.base_type == "ref":
            return self._sanitize_name(cddl_type.reference or "Any")
        
        if cddl_type.base_type == "map":
            return "Dict[str, Any]"
        
        return "Any"

    def _sanitize_name(self, name: str) -> str:
        """Sanitize a type name for use in Python.
        
        Args:
            name: Original CDDL type name
            
        Returns:
            Sanitized Python type name
        """
        if not name:
            return "Any"
        
        # Remove module prefix (e.g., "session.New" -> "SessionNew")
        parts = name.split(".")
        result = "".join(part.capitalize() for part in parts)
        
        # Remove non-alphanumeric characters
        result = "".join(c for c in result if c.isalnum())
        
        # Ensure it starts with a letter
        if result and not result[0].isalpha():
            result = "T" + result
        
        return result or "Any"

    def _sanitize_identifier(self, name: str) -> str:
        """Sanitize a name for use as a Python identifier.
        
        Args:
            name: Original name
            
        Returns:
            Sanitized identifier
        """
        # Replace special characters with underscores
        result = ""
        for char in name:
            if char.isalnum() or char == "_":
                result += char
            else:
                result += "_"
        
        # Remove consecutive underscores
        while "__" in result:
            result = result.replace("__", "_")
        
        # Remove leading/trailing underscores
        result = result.strip("_")
        
        # Ensure it doesn't start with a digit
        if result and result[0].isdigit():
            result = "_" + result
        
        return result or "unknown"

