package org.openqa.selenium.locator.bidi.selenium.adapter;

enum RawBidiEventType {
  NETWORK_BEFORE_REQUEST,
  NETWORK_RESPONSE_STARTED,
  NETWORK_RESPONSE_COMPLETED,
  NETWORK_FETCH_ERROR,
  CONSOLE,
  NAVIGATION_STARTED,
  NAVIGATION_COMMITTED,
  NAVIGATION_DOM_CONTENT_LOADED,
  NAVIGATION_LOADED,
  HISTORY_UPDATED
}
